[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "65.108.217.133"
Port = "5435"
MaxConns = 20

[ClaimTxManager]
Enabled = true
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "./sequence.keystore", Password = "testonly"} #trusted sequencer private key
RetryInterval = "1s"
RetryNumber = 10
AuthorizedClaimMessageAddresses = ["0x20b8c692d9d4441f0ca954320e156d8f0d86e873"] #trusted sequencer address

[Etherman]
L1URL = "https://powerful-aged-asphalt.ethereum-sepolia.quiknode.pro/c098b6f06418c7a2e872d7ddf99fe756a613257a/"
L2URLs = ["http://95.217.14.162:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "65.108.217.133"
    Port = "5435"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 5195006
PolygonBridgeAddress = "0x235EC2dC686BcF20D676Ce4cFcC8827db16F5917"
PolygonZkEVMGlobalExitRootAddress = "0xF6E2f8a996c2B832e58996e36952cd0c8a08e82D"
L2PolygonBridgeAddresses = ["0x235EC2dC686BcF20D676Ce4cFcC8827db16F5917"]

